=== mklump/CS_OIT2005Degree_Accademic_Work/CST 407 Java J2EE/examples/chapters/DeitelBookstore/clients.dtd
<!-- clients.dtd                               -->
<!-- DTD for specifying Bookstore client types -->

<!ELEMENT clients ( client+ )>

<!ELEMENT client ( userAgent, contentType, XSLPath )>
<!ATTLIST client name CDATA #REQUIRED>

<!ELEMENT userAgent ( #PCDATA )>
<!ELEMENT contentType ( #PCDATA )>
<!ELEMENT XSLPath ( #PCDATA )>

=== mklump/CS_OIT2005Degree_Accademic_Work/CST 407 Java J2EE/examples/chapters/DeitelBookstore/clients.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE clients SYSTEM 
   "http://www.deitel.com/advjhtp1/clients.dtd">

<!-- Client configuration file for the Deitel Bookstore -->

<clients>

   <!-- Microsoft Internet Explorer version 5 client -->
   <client name = "Microsoft Internet Explorer 5">
      <userAgent>Mozilla/4.0 (compatible; MSIE 5</userAgent>
      <contentType>text/html</contentType>
      <XSLPath>/XSLT/XHTML/</XSLPath>
   </client>

   <!-- Microsoft Internet Explorer version 6 client -->
   <client name = "Microsoft Internet Explorer 6">
      <userAgent>Mozilla/4.0 (compatible; MSIE 6</userAgent>
      <contentType>text/html</contentType>
      <XSLPath>/XSLT/XHTML/</XSLPath>
   </client>

   <!-- Netscape version 4.7x client -->
   <client name = "Netscape 4.7">
      <userAgent>Mozilla/4.7</userAgent>
      <contentType>text/html</contentType>
      <XSLPath>/XSLT/XHTML/</XSLPath>
   </client>

   <!-- Mozilla/Netscape version 6 client -->
   <client name = "Mozilla/Netscape 6">
      <userAgent>Gecko</userAgent>
      <contentType>text/html</contentType>
      <XSLPath>/XSLT/XHTML/</XSLPath>
   </client>

   <!-- Phone.com WML browser client -->
   <client name = "Openwave SDK Browser">
      <userAgent>UP.Browser/4</userAgent>
      <contentType>text/vnd.wap.wml</contentType>
      <XSLPath>/XSLT/WML/</XSLPath>
   </client>

   <!-- Nokia WML browser client -->
   <client name = "Nokia WAP Toolkit Browser">
      <userAgent>Nokia-WAP</userAgent>
      <contentType>text/vnd.wap.wml</contentType>
      <XSLPath>/XSLT/WML/</XSLPath>
   </client>

   <!-- Pixo iMode browser client -->
   <client name = "Pixo Browser">
      <userAgent>Pixo-Browser</userAgent>
      <contentType>text/html</contentType>
      <XSLPath>/XSLT/cHTML/</XSLPath>
   </client>
<!-- 
  (C) Copyright 2001 by Deitel & Associates, Inc. and         
  Prentice Hall. All Rights Reserved.                         
                                                              
  DISCLAIMER: The authors and publisher of this book have     
  used their best efforts in preparing the book. These        
  efforts include the development, research, and testing of   
  the theories and programs to determine their effectiveness. 
  The authors and publisher make no warranty of any kind,     
  expressed or implied, with regard to these programs or to   
  the documentation contained in these books. The authors     
  and publisher shall not be liable in any event for          
  incidental or consequential damages in connection with, or  
  arising out of, the furnishing, performance, or use of      
  these programs.                                             
 -->

</clients>
